- wrist_mounted_camera:
    camera_name: "wrist_mounted_camera"
    type: "sim"
    use: True

    # These values must match those specified in realsense_d415.urdf.xacro
    image_width: 640
    image_height: 480

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/wrist_mounted_camera/color/camera_info"
    rgb_image: "/wrist_mounted_camera/color/image_raw"

    # By adding registered_rgb_depth_pair, this camera can be used for "Set Transform From Click"
    # Since this is simulation, assume registered image is simply the raw image.
    registered_rgb_depth_pair:
      depth_info: "/wrist_mounted_camera/color/camera_info"
      depth_image: "/wrist_mounted_camera/depth/image_rect_raw"
      registered_info: "/wrist_mounted_camera/depth_registered/camera_info"
      registered_image: "/wrist_mounted_camera/depth_registered/image_rect_raw"
