#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "ur_base_config"

hardware:
  simulated: ${MOCK_HARDWARE:-true}
  ip: 192.10.0.11
  camera_config_file:
    package: "ur_hardware_config"
    path: "config/cameras.yaml"
  robot_description:
    urdf:
      package: "ur_hardware_config"
      path: "description/picknik_007_ur5e.xacro"
    srdf:
      package: "ur_hardware_config"
      path: "config/moveit/picknik_007_ur5e.srdf"
    urdf_params:
      - kinematics_parameters_file:
          package: "ur_hardware_config"
          path: "calibration/kinematic_calibration.yaml"

  hardware_launch_file:
    package: "ur_hardware_config"
    path: "launch/bringup.launch.py"

objectives:
  waypoints_file:
    package_name: "ur_hardware_config"
    relative_path: "waypoints/waypoints.yaml"
  objective_library_paths:
    007:
      package_name: "ur_hardware_config"
      relative_path: "objectives"
